//! The back-compat half of the config convention, made checkable (FRE-120).
//!
//! Every new field on a config type is declared `#[serde(default,
//! skip_serializing_if = ...)]` so **older config files still deserialize and
//! unaffected entries serialize unchanged**. The first half is easy to assert
//! and easy to believe; the second is the one that quietly breaks, because a
//! field that starts serializing an implicit default rewrites every user's
//! file on the next save.
//!
//! `tests/fixtures/connections_pre_fre_120.toml` is a real connections.toml
//! written by the code as it stood *before* groups existed — SQLite, Postgres
//! with an SSH tunnel, SQL Server with Entra, and FRE-111 markings. Loading it
//! and saving it back must reproduce it byte for byte.

use std::path::Path;

use hubro::config::{load_connections, save_connections, SavedList};

const FIXTURE: &str = "tests/fixtures/connections_pre_fre_120.toml";

/// The fixture, copied into a temp dir so the test writes over its own copy
/// and never the checked-in one.
fn fixture_copy(dir: &Path) -> std::path::PathBuf {
    let original = std::fs::read_to_string(FIXTURE).expect("the fixture is checked in");
    let path = dir.join("connections.toml");
    std::fs::write(&path, original).unwrap();
    path
}

#[test]
fn a_pre_group_connections_file_round_trips_byte_for_byte() {
    let dir = tempfile::tempdir().unwrap();
    let path = fixture_copy(dir.path());
    let before = std::fs::read_to_string(&path).unwrap();

    // The plain serde route: load the entries, write them back.
    let entries = load_connections(&path).expect("a pre-FRE-120 file still loads");
    assert_eq!(entries.len(), 5, "every entry survived the load");
    save_connections(&path, &entries).unwrap();
    assert_eq!(
        std::fs::read_to_string(&path).unwrap(),
        before,
        "an untouched pre-FRE-120 file must be rewritten unchanged"
    );

    // And the route the app actually takes, which additionally normalizes
    // URLs and writes the group list.
    let (list, error) = SavedList::load(&path);
    assert_eq!(error, None);
    assert!(list.groups().is_empty(), "the file declares no groups");
    for entry in list.entries() {
        assert_eq!(entry.group(), None, "{}", entry.name());
    }
    list.persist(&path).unwrap();
    assert_eq!(
        std::fs::read_to_string(&path).unwrap(),
        before,
        "saving a group-less list must not add a groups key"
    );
}

#[test]
fn the_fixture_predates_groups() {
    // Guards the test above from becoming a tautology: if the fixture were
    // ever regenerated by a build that writes groups, the round trip would
    // still pass while checking nothing about older files.
    let text = std::fs::read_to_string(FIXTURE).unwrap();
    assert!(!text.contains("group"), "{text}");
    // …and it is rich enough to be worth round-tripping: the optional keys
    // that already exist all appear in it.
    for key in [
        "kind = \"sqlite\"",
        "kind = \"postgres\"",
        "kind = \"sqlserver\"",
        "[connections.tunnel]",
        "kind = \"entra\"",
        "protection = ",
        "color = ",
    ] {
        assert!(text.contains(key), "the fixture is missing {key}");
    }
}
