//! Backend-neutral schema metadata. Captures primary keys, unique indexes,
//! and foreign keys up front — editing and FK navigation depend on them.

use super::caps::Restriction;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TableKind {
    Table,
    View,
    /// A Postgres materialized view (`pg_class.relkind = 'm'`): browsable like a
    /// table but read-only — no editing, no row-identity writes (FRE-41).
    MaterializedView,
}

/// Whether the database assigns a column's value itself, and whether the
/// user may override it. Drives insert required-column detection and
/// editor read-only gating (FRE-25).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Generated {
    /// An ordinary column the user writes directly.
    #[default]
    Never,
    /// Auto-assigned but user-overridable: `GENERATED BY DEFAULT AS
    /// IDENTITY` (`serial`, whose value is a real `nextval(…)` default, is
    /// represented as `Never` with a `default` instead). Not required for
    /// inserts; still editable.
    ByDefault,
    /// Always assigned by the database and not writable through ordinary
    /// INSERT/UPDATE: `GENERATED ALWAYS AS IDENTITY` and `GENERATED ALWAYS
    /// AS (expr) STORED`. Not required for inserts; read-only in the editor.
    Always,
}

/// A schema-qualified type name straight from `pg_catalog`. Both halves are
/// arbitrary SQL identifiers — `CREATE TYPE "Mood"` and quoted names with
/// spaces or hyphens are all legal — so they are kept apart and quoted at
/// the point of use rather than pre-joined into one string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeRef {
    pub schema: String,
    pub name: String,
}

/// Type structure that the declared type name alone doesn't convey, used to
/// pick a richer editor (FRE-71). Postgres reports both of these as opaque
/// `information_schema` strings (`USER-DEFINED`, `ARRAY`), so the detail is
/// resolved during introspection; backends without these types report
/// [`TypeDetail::Plain`].
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum TypeDetail {
    /// Nothing beyond the type name — the editor follows from it alone.
    #[default]
    Plain,
    /// An enum type: its variants in declaration order, plus the real type
    /// name staged values must be cast to, since `data_type` only says
    /// `USER-DEFINED`.
    Enum {
        type_ref: TypeRef,
        variants: Vec<String>,
    },
    /// An array type, with the real type name to cast to (e.g.
    /// `pg_catalog._text`); `data_type` only says `ARRAY`.
    Array { type_ref: TypeRef },
}

impl TypeDetail {
    /// The real type name staged values must be cast to, when the declared
    /// `type_name` isn't itself a usable cast target.
    pub fn cast_type(&self) -> Option<&TypeRef> {
        match self {
            TypeDetail::Plain => None,
            TypeDetail::Enum { type_ref, .. } | TypeDetail::Array { type_ref } => Some(type_ref),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnMeta {
    pub name: String,
    /// Declared type as written in the schema (may be empty in SQLite).
    pub type_name: String,
    pub nullable: bool,
    /// 1-based position within the primary key; `None` when not part of it.
    pub primary_key_position: Option<u32>,
    /// Default value expression as written in the schema, if any (e.g. a
    /// Postgres `serial`'s `nextval(…)`). Database-assigned identity and
    /// generated columns, which have no literal default, are marked via
    /// [`ColumnMeta::generated`] instead.
    pub default: Option<String>,
    /// Whether the database assigns this column's value — see [`Generated`].
    pub generated: Generated,
    /// Enum/array structure behind an opaque `type_name` — see [`TypeDetail`].
    pub type_detail: TypeDetail,
}

impl ColumnMeta {
    /// Whether the database supplies this column's value on insert without
    /// the user having to (a real default, an identity column, a generated
    /// column). Such columns are never "required" for a pending insert.
    pub fn is_auto_assigned(&self) -> bool {
        self.default.is_some() || self.generated != Generated::Never
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexMeta {
    pub name: String,
    pub unique: bool,
    /// Partial index (`CREATE INDEX … WHERE predicate`). A partial unique
    /// index only guarantees uniqueness among the rows matching its
    /// predicate, so row identity (rowkey.rs) must never rely on one.
    pub partial: bool,
    pub columns: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForeignKeyMeta {
    /// Referencing columns in this table, in key order.
    pub columns: Vec<String>,
    /// Schema of the referenced table (`None` on backends without schemas).
    pub referenced_schema: Option<String>,
    pub referenced_table: String,
    /// Referenced columns, parallel to `columns`. An entry is `None` when the
    /// FK references the target table's implicit primary key.
    pub referenced_columns: Vec<Option<String>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableMeta {
    /// Schema the table lives in (`None` on backends without schemas, i.e.
    /// SQLite).
    pub schema: Option<String>,
    pub name: String,
    pub kind: TableKind,
    pub columns: Vec<ColumnMeta>,
    pub indexes: Vec<IndexMeta>,
    pub foreign_keys: Vec<ForeignKeyMeta>,
    /// Per-object narrowing of the connection's capabilities, resolved during
    /// introspection (FRE-87) — `None` when the object follows its
    /// connection's defaults.
    ///
    /// Only for limits the driver knows and the resolver cannot derive on its
    /// own: [`TableKind`] and row identity are already handled by
    /// [`TableAccess::resolve`], so the three current backends leave this
    /// `None`. It exists for engines whose writability varies per object — a
    /// StarRocks duplicate-key table, a DuckDB view over a Parquet file, a
    /// Materialize source.
    ///
    /// [`TableAccess::resolve`]: super::caps::TableAccess::resolve
    pub restriction: Option<Restriction>,
    /// The extension whose schema owns this object, when one does (FRE-88):
    /// TimescaleDB's chunk tables in `_timescaledb_internal`, PostGIS's
    /// `tiger`, Citus's catalogs. These are real, queryable objects — an
    /// extension's bookkeeping rather than the user's data, and numerous
    /// enough to bury it (a Timescale database with 40 days of daily chunks
    /// reports 95 of them against 4 user tables).
    ///
    /// Recorded rather than filtered out during introspection so nothing
    /// silently disappears: the sidebar hides these by default and says how
    /// many it hid, and the SQL editor still completes them.
    ///
    /// `None` for ordinary user schemas, and always `None` on backends with
    /// no extension concept (SQLite, SQL Server).
    pub extension: Option<String>,
}

impl TableMeta {
    /// Columns making up the primary key, in key order.
    pub fn primary_key(&self) -> Vec<&ColumnMeta> {
        let mut pk: Vec<&ColumnMeta> = self
            .columns
            .iter()
            .filter(|c| c.primary_key_position.is_some())
            .collect();
        pk.sort_by_key(|c| c.primary_key_position);
        pk
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, pk: Option<u32>) -> ColumnMeta {
        ColumnMeta {
            name: name.into(),
            type_name: "TEXT".into(),
            nullable: true,
            primary_key_position: pk,
            default: None,
            generated: Generated::Never,
            type_detail: TypeDetail::Plain,
        }
    }

    #[test]
    fn primary_key_is_ordered_by_key_position() {
        let table = TableMeta {
            schema: None,
            name: "t".into(),
            kind: TableKind::Table,
            columns: vec![col("a", Some(2)), col("b", None), col("c", Some(1))],
            indexes: vec![],
            foreign_keys: vec![],
            restriction: None,
            extension: None,
        };
        let pk: Vec<&str> = table
            .primary_key()
            .iter()
            .map(|c| c.name.as_str())
            .collect();
        assert_eq!(pk, ["c", "a"]);
    }
}
