//! Backend-neutral schema metadata. Captures primary keys, unique indexes,
//! and foreign keys up front — editing and FK navigation depend on them.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TableKind {
    Table,
    View,
    /// A Postgres materialized view (`pg_class.relkind = 'm'`): browsable like a
    /// table but read-only — no editing, no row-identity writes (FRE-41).
    MaterializedView,
}

/// Whether the database assigns a column's value itself, and whether the
/// user may override it. Drives insert required-column detection and
/// editor read-only gating (FRE-25).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Generated {
    /// An ordinary column the user writes directly.
    #[default]
    Never,
    /// Auto-assigned but user-overridable: `GENERATED BY DEFAULT AS
    /// IDENTITY` (`serial`, whose value is a real `nextval(…)` default, is
    /// represented as `Never` with a `default` instead). Not required for
    /// inserts; still editable.
    ByDefault,
    /// Always assigned by the database and not writable through ordinary
    /// INSERT/UPDATE: `GENERATED ALWAYS AS IDENTITY` and `GENERATED ALWAYS
    /// AS (expr) STORED`. Not required for inserts; read-only in the editor.
    Always,
}

/// Type structure that the declared type name alone doesn't convey, used to
/// pick a richer editor (FRE-71). Postgres reports both of these as opaque
/// `information_schema` strings (`USER-DEFINED`, `ARRAY`), so the detail is
/// resolved during introspection; backends without these types report
/// [`TypeDetail::Plain`].
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum TypeDetail {
    /// Nothing beyond the type name — the editor follows from it alone.
    #[default]
    Plain,
    /// An enum type: its variants in declaration order, plus the
    /// schema-qualified type name (e.g. `public.mood`) that staged values
    /// must be cast to, since `data_type` only says `USER-DEFINED`.
    Enum {
        type_name: String,
        variants: Vec<String>,
    },
    /// An array type, with the schema-qualified type name to cast to (e.g.
    /// `pg_catalog._text`); `data_type` only says `ARRAY`.
    Array { type_name: String },
}

impl TypeDetail {
    /// The schema-qualified type name staged values must be cast to, when
    /// the declared `type_name` isn't itself a usable cast target.
    pub fn cast_name(&self) -> Option<&str> {
        match self {
            TypeDetail::Plain => None,
            TypeDetail::Enum { type_name, .. } | TypeDetail::Array { type_name } => {
                Some(type_name.as_str())
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnMeta {
    pub name: String,
    /// Declared type as written in the schema (may be empty in SQLite).
    pub type_name: String,
    pub nullable: bool,
    /// 1-based position within the primary key; `None` when not part of it.
    pub primary_key_position: Option<u32>,
    /// Default value expression as written in the schema, if any (e.g. a
    /// Postgres `serial`'s `nextval(…)`). Database-assigned identity and
    /// generated columns, which have no literal default, are marked via
    /// [`ColumnMeta::generated`] instead.
    pub default: Option<String>,
    /// Whether the database assigns this column's value — see [`Generated`].
    pub generated: Generated,
    /// Enum/array structure behind an opaque `type_name` — see [`TypeDetail`].
    pub type_detail: TypeDetail,
}

impl ColumnMeta {
    /// Whether the database supplies this column's value on insert without
    /// the user having to (a real default, an identity column, a generated
    /// column). Such columns are never "required" for a pending insert.
    pub fn is_auto_assigned(&self) -> bool {
        self.default.is_some() || self.generated != Generated::Never
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexMeta {
    pub name: String,
    pub unique: bool,
    /// Partial index (`CREATE INDEX … WHERE predicate`). A partial unique
    /// index only guarantees uniqueness among the rows matching its
    /// predicate, so row identity (rowkey.rs) must never rely on one.
    pub partial: bool,
    pub columns: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForeignKeyMeta {
    /// Referencing columns in this table, in key order.
    pub columns: Vec<String>,
    /// Schema of the referenced table (`None` on backends without schemas).
    pub referenced_schema: Option<String>,
    pub referenced_table: String,
    /// Referenced columns, parallel to `columns`. An entry is `None` when the
    /// FK references the target table's implicit primary key.
    pub referenced_columns: Vec<Option<String>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableMeta {
    /// Schema the table lives in (`None` on backends without schemas, i.e.
    /// SQLite).
    pub schema: Option<String>,
    pub name: String,
    pub kind: TableKind,
    pub columns: Vec<ColumnMeta>,
    pub indexes: Vec<IndexMeta>,
    pub foreign_keys: Vec<ForeignKeyMeta>,
}

impl TableMeta {
    /// Columns making up the primary key, in key order.
    pub fn primary_key(&self) -> Vec<&ColumnMeta> {
        let mut pk: Vec<&ColumnMeta> = self
            .columns
            .iter()
            .filter(|c| c.primary_key_position.is_some())
            .collect();
        pk.sort_by_key(|c| c.primary_key_position);
        pk
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, pk: Option<u32>) -> ColumnMeta {
        ColumnMeta {
            name: name.into(),
            type_name: "TEXT".into(),
            nullable: true,
            primary_key_position: pk,
            default: None,
            generated: Generated::Never,
            type_detail: TypeDetail::Plain,
        }
    }

    #[test]
    fn primary_key_is_ordered_by_key_position() {
        let table = TableMeta {
            schema: None,
            name: "t".into(),
            kind: TableKind::Table,
            columns: vec![col("a", Some(2)), col("b", None), col("c", Some(1))],
            indexes: vec![],
            foreign_keys: vec![],
        };
        let pk: Vec<&str> = table
            .primary_key()
            .iter()
            .map(|c| c.name.as_str())
            .collect();
        assert_eq!(pk, ["c", "a"]);
    }
}
