-- Demo schema + data for manual testing of hubro against Postgres.
--
-- Applied by seed-postgres.sh; re-running drops and recreates everything it
-- owns, so it is safe to run repeatedly.
--
-- Deliberately covers the things the viewer has special handling for: multiple
-- schemas, views and materialized views, identity/generated columns, composite
-- and text primary keys, a keyless table, foreign keys (single and composite),
-- a partial unique index, enum and array types, NULLs, unicode, oversized
-- cells, and a table big enough to page through.

-- Quiet the "does not exist, skipping" notices from the first run's drops.
SET client_min_messages = warning;

DROP MATERIALIZED VIEW IF EXISTS analytics.customer_totals;
DROP VIEW IF EXISTS order_summary;
DROP SCHEMA IF EXISTS analytics CASCADE;
DROP TABLE IF EXISTS order_items, orders, events, products, customers, all_types, sensor_readings CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;

CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled', 'refunded');

-- ---------------------------------------------------------------- customers
-- Overridable identity PK, a unique constraint, arrays, jsonb, bytea, NULLs.
CREATE TABLE customers (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text NOT NULL,
    email     text NOT NULL UNIQUE,
    signed_up date NOT NULL DEFAULT CURRENT_DATE,
    is_active boolean NOT NULL DEFAULT true,
    balance   numeric(12, 2) NOT NULL DEFAULT 0,
    tags      text[],
    prefs     jsonb,
    notes     text,
    avatar    bytea
);

INSERT INTO customers (id, name, email, signed_up, is_active, balance, tags, prefs, notes, avatar) VALUES
    (1,  'Ada Lovelace',    'ada@example.com',    '2021-03-14', true,   1250.00, '{vip,beta}',       '{"theme":"dark","locale":"en"}',  'First customer.',                          '\x89504e470d0a1a0a'),
    (2,  'Ingrid Hågensen', 'ingrid@example.no',  '2022-01-02', true,      0.00, '{}',               '{"theme":"light"}',               NULL,                                       NULL),
    (3,  '张伟',            'zhang@example.cn',   '2022-06-30', true,    -42.50, '{wholesale}',      NULL,                              'Bills in CNY. 中文备注。',                  NULL),
    (4,  'Björn Öst',       'bjorn@example.se',   '2023-02-11', false,   310.75, '{lapsed}',         '{"theme":"dark","digest":false}', 'Churned after the 2023 price change.',     NULL),
    (5,  'Yusuf Al-Amin',   'yusuf@example.ae',   '2023-04-19', true,     88.20, '{vip}',            '{"locale":"ar"}',                 NULL,                                       '\xffd8ffe000104a46'),
    (6,  'Emoji Enjoyer 🦉','owl@example.com',    '2023-08-08', true,      5.00, '{beta,noisy,"has space"}', '{"emoji":"🦉🎉"}',        'Name and prefs both contain emoji 🎉',      NULL),
    (7,  'Mara Silva',      'mara@example.br',    '2024-01-05', true,   2400.00, '{vip,wholesale}',  '{"theme":"system"}',              NULL,                                       NULL),
    (8,  'Tom O''Brien',    'tom@example.ie',     '2024-03-22', true,     19.99, NULL,               NULL,                              'Apostrophe in the name, on purpose.',      NULL),
    (9,  'Nadia Petrova',   'nadia@example.ru',   '2024-07-17', false,     0.00, '{lapsed}',         '{}',                              NULL,                                       NULL),
    (10, 'Kenji Watanabe',  'kenji@example.jp',   '2025-02-09', true,    640.10, '{beta}',           '{"locale":"ja","theme":"dark"}',  repeat('A very long note that should be truncated in the grid and readable in the cell editor. ', 40), NULL),
    (11, 'Sofia Rossi',     'sofia@example.it',   '2025-05-30', true,    120.00, '{}',               '{"digest":true}',                 NULL,                                       NULL),
    (12, 'No Contact',      'void@example.com',   '2025-11-11', false,     0.00, NULL,               NULL,                              NULL,                                       NULL);

ALTER TABLE customers ALTER COLUMN id RESTART WITH 13;

-- ----------------------------------------------------------------- products
-- Text primary key, so FKs point at something other than an integer.
CREATE TABLE products (
    sku             varchar(16) PRIMARY KEY,
    name            text NOT NULL,
    price           numeric(10, 2) NOT NULL CHECK (price >= 0),
    weight_kg       real,
    in_stock        integer NOT NULL DEFAULT 0,
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb,
    discontinued_at timestamptz
);

INSERT INTO products (sku, name, price, weight_kg, in_stock, attributes, discontinued_at) VALUES
    ('KB-60',    'Keyboard, 60%',       89.00,  0.55,  120, '{"switches":"tactile","layout":"ansi"}', NULL),
    ('KB-TKL',   'Keyboard, TKL',      119.00,  0.82,   45, '{"switches":"linear","layout":"iso"}',   NULL),
    ('MS-ERG',   'Mouse, ergonomic',    69.50,  0.11,    0, '{"buttons":6}',                          NULL),
    ('MS-TRK',   'Trackball',           94.00,  0.24,   12, '{"buttons":5,"ball":"55mm"}',            NULL),
    ('MON-27',   'Monitor 27" 4K',     549.00,  6.30,    8, '{"panel":"IPS","hz":60}',                NULL),
    ('MON-34U',  'Monitor 34" ultra',  899.00,  9.10,    3, '{"panel":"OLED","hz":175}',              NULL),
    ('CAB-USBC', 'Cable, USB-C 2m',      19.90, 0.09,  500, '{"length_m":2}',                         NULL),
    ('DOK-TB4',  'Dock, Thunderbolt 4',279.00,  0.65,   22, '{"ports":11}',                           NULL),
    ('HP-OLD',   'Headphones (EOL)',    59.00,  0.31,    0, '{"eol":true}',                           '2024-09-01 12:00:00+02'),
    ('MAT-DSK',  'Desk mat, felt',      34.00,  0.40,   77, '{"colour":"grå","size":"90x40"}',        NULL);

-- ------------------------------------------------------------------- orders
-- Non-overridable identity (read-only in the editor), an enum column, and a
-- partial unique index (at most one pending order per customer) that row
-- identity must not mistake for a usable key.
CREATE TABLE orders (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
    status      order_status NOT NULL DEFAULT 'pending',
    placed_at   timestamptz NOT NULL DEFAULT now(),
    ship_to     text,
    coupon      text
);

CREATE INDEX orders_customer_idx ON orders (customer_id);
CREATE UNIQUE INDEX orders_one_pending_per_customer ON orders (customer_id) WHERE status = 'pending';

INSERT INTO orders (id, customer_id, status, placed_at, ship_to, coupon)
OVERRIDING SYSTEM VALUE
SELECT i,
       1 + (i % 12),
       (ARRAY['paid', 'shipped', 'cancelled', 'refunded']::order_status[])[1 + (i % 4)],
       now() - (i || ' days')::interval,
       CASE WHEN i % 5 = 0 THEN NULL ELSE 'Storgata ' || i || ', Oslo' END,
       CASE WHEN i % 6 = 0 THEN 'SUMMER10' END
FROM generate_series(1, 40) AS g (i);

INSERT INTO orders (id, customer_id, status, placed_at, ship_to)
OVERRIDING SYSTEM VALUE
VALUES (41, 1, 'pending', now() - interval '2 hours', 'Storgata 1, Oslo'),
       (42, 2, 'pending', now() - interval '20 minutes', NULL),
       (43, 3, 'pending', now(), 'Bryggen 4, Bergen');

ALTER TABLE orders ALTER COLUMN id RESTART WITH 44;

-- -------------------------------------------------------------- order_items
-- Composite primary key, two foreign keys, and a stored generated column.
CREATE TABLE order_items (
    order_id   bigint NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    line_no    smallint NOT NULL,
    sku        varchar(16) NOT NULL REFERENCES products (sku),
    quantity   integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price numeric(10, 2) NOT NULL,
    line_total numeric(12, 2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    PRIMARY KEY (order_id, line_no)
);

INSERT INTO order_items (order_id, line_no, sku, quantity, unit_price)
SELECT o.id, n::smallint, p.sku, 1 + ((o.id + n) % 4), p.price
FROM orders o
CROSS JOIN generate_series(1, 3) AS g (n)
CROSS JOIN LATERAL (
    SELECT sku, price FROM products
    ORDER BY sku
    OFFSET (o.id * 3 + n) % (SELECT count(*) FROM products) LIMIT 1
) p
WHERE (o.id + n) % 3 <> 0;

-- ------------------------------------------------------------------- events
-- No primary key and no unique index, so rows are addressed by ctid — and big
-- enough to page, sort and filter through.
CREATE TABLE events (
    occurred_at timestamptz NOT NULL,
    kind        text NOT NULL,
    customer_id integer REFERENCES customers (id),
    payload     jsonb,
    duration_ms integer
);

INSERT INTO events (occurred_at, kind, customer_id, payload, duration_ms)
SELECT now() - (i || ' minutes')::interval,
       (ARRAY['page_view', 'click', 'signup', 'purchase', 'error'])[1 + (i % 5)],
       CASE WHEN i % 7 = 0 THEN NULL ELSE 1 + (i % 12) END,
       jsonb_build_object('seq', i, 'ok', i % 3 <> 0, 'path', '/p/' || (i % 50)),
       CASE WHEN i % 11 = 0 THEN NULL ELSE (i * 7) % 900 END
FROM generate_series(1, 5000) AS g (i);

CREATE INDEX events_occurred_idx ON events (occurred_at);

-- ---------------------------------------------------------- sensor_readings
-- Composite foreign key target for the analytics schema, and a table whose
-- only unique index (not a PK) has to serve as row identity.
CREATE TABLE sensor_readings (
    site       text NOT NULL,
    sensor     text NOT NULL,
    reading_at timestamp NOT NULL,
    celsius    double precision,
    humidity   double precision
);

CREATE UNIQUE INDEX sensor_readings_key ON sensor_readings (site, sensor, reading_at);

INSERT INTO sensor_readings (site, sensor, reading_at, celsius, humidity)
SELECT s.site, 'probe-' || p,
       timestamp '2026-01-01 00:00' + (h || ' hours')::interval,
       round((15 + 10 * sin(h / 3.0) + p)::numeric, 2),
       CASE WHEN h % 9 = 0 THEN NULL ELSE round((40 + 20 * cos(h / 5.0))::numeric, 2) END
FROM (VALUES ('oslo'), ('bergen'), ('tromsø')) AS s (site),
     generate_series(1, 3) AS gp (p),
     generate_series(0, 199) AS gh (h);

-- ---------------------------------------------------------------- all_types
-- One row of ordinary values, one all-NULL row, one row of extremes. Includes
-- types with no dedicated decoder (point, money, xml, bit, tsvector, inet) so
-- the display fallbacks get exercised too.
CREATE TABLE all_types (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label        text,
    c_smallint   smallint,
    c_integer    integer,
    c_bigint     bigint,
    c_numeric    numeric(20, 6),
    c_real       real,
    c_double     double precision,
    c_bool       boolean,
    c_char       char(4),
    c_varchar    varchar(32),
    c_text       text,
    c_bytea      bytea,
    c_date       date,
    c_time       time,
    c_timetz     timetz,
    c_timestamp  timestamp,
    c_timestamptz timestamptz,
    c_interval   interval,
    c_uuid       uuid,
    c_json       json,
    c_jsonb      jsonb,
    c_text_arr   text[],
    c_int_arr    integer[],
    c_enum       order_status,
    c_inet       inet,
    c_macaddr    macaddr,
    c_point      point,
    c_money      money,
    c_xml        xml,
    c_bit        bit(8),
    c_tsvector   tsvector
);

INSERT INTO all_types (id, label, c_smallint, c_integer, c_bigint, c_numeric, c_real, c_double,
                       c_bool, c_char, c_varchar, c_text, c_bytea, c_date, c_time, c_timetz,
                       c_timestamp, c_timestamptz, c_interval, c_uuid, c_json, c_jsonb,
                       c_text_arr, c_int_arr, c_enum, c_inet, c_macaddr, c_point, c_money,
                       c_xml, c_bit, c_tsvector)
VALUES
    (1, 'typical', 42, 123456, 9007199254740993, 1234.567890, 3.5, 2.718281828459045,
     true, 'abcd', 'varchar value', 'plain text', '\xdeadbeef', '2026-02-14', '13:45:00', '13:45:00+01',
     '2026-02-14 13:45:00.123', '2026-02-14 13:45:00.123+01', '1 day 02:03:04', '3f333df6-90a4-4fda-8dd3-9485d27cee36',
     '{"a":[1,2,3]}', '{"b":{"c":true}}', '{one,two,"with space"}', '{1,2,3}', 'shipped',
     '192.168.1.42', '08:00:2b:01:02:03', '(1.5,-2.5)', 1234.56, '<note>hi</note>', B'10110011',
     to_tsvector('english', 'the quick brown fox')),
    (2, 'all null', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
     NULL, NULL),
    (3, 'extremes', -32768, -2147483648, -9223372036854775808, -99999999999999.999999, 'Infinity'::real, 'NaN'::double precision,
     false, '  x ', 'ünïcödé — 中文 — 🦉', repeat('long cell. ', 900), decode(repeat('00ff', 4000), 'hex'),
     'infinity'::date, '00:00:00', '23:59:59.999999-11',
     'infinity'::timestamp, '-infinity'::timestamptz, '-3 years 4 mons 5 days -06:07:08',
     '00000000-0000-0000-0000-000000000000', 'null', '[]',
     '{NULL,"",tab\there}', '{}', 'refunded',
     '2001:db8::1/128', 'ff:ff:ff:ff:ff:ff', '(0,0)', -0.01, '<empty/>', B'00000000',
     to_tsvector('simple', 'åäö'));

ALTER TABLE all_types ALTER COLUMN id RESTART WITH 4;

-- --------------------------------------------------------------------- view
CREATE VIEW order_summary AS
SELECT o.id AS order_id,
       c.name AS customer,
       o.status,
       o.placed_at,
       count(i.line_no) AS lines,
       coalesce(sum(i.line_total), 0) AS total
FROM orders o
JOIN customers c ON c.id = o.customer_id
LEFT JOIN order_items i ON i.order_id = o.id
GROUP BY o.id, c.name, o.status, o.placed_at;

-- ------------------------------------------------------- analytics (schema)
CREATE SCHEMA analytics;

CREATE TABLE analytics.daily_sales (
    day     date NOT NULL,
    sku     varchar(16) NOT NULL REFERENCES public.products (sku),
    units   integer NOT NULL,
    revenue numeric(12, 2) NOT NULL,
    PRIMARY KEY (day, sku)
);

INSERT INTO analytics.daily_sales (day, sku, units, revenue)
SELECT d::date, p.sku, u.units, round(u.units * p.price, 2)
FROM generate_series(timestamp '2026-01-01', timestamp '2026-03-31', interval '1 day') AS g (d)
CROSS JOIN products p
CROSS JOIN LATERAL (SELECT (extract(day FROM d)::int * length(p.sku)) % 17 AS units) u
WHERE p.discontinued_at IS NULL;

-- Composite FK into sensor_readings' unique index, to exercise multi-column
-- foreign-key navigation.
CREATE TABLE analytics.sensor_alerts (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site       text NOT NULL,
    sensor     text NOT NULL,
    reading_at timestamp NOT NULL,
    severity   text NOT NULL,
    FOREIGN KEY (site, sensor, reading_at)
        REFERENCES public.sensor_readings (site, sensor, reading_at)
);

INSERT INTO analytics.sensor_alerts (site, sensor, reading_at, severity)
SELECT site, sensor, reading_at,
       CASE WHEN celsius > 24 THEN 'critical' ELSE 'warning' END
FROM sensor_readings
WHERE celsius > 23
ORDER BY reading_at
LIMIT 60;

CREATE MATERIALIZED VIEW analytics.customer_totals AS
SELECT c.id,
       c.name,
       count(DISTINCT o.id) AS orders,
       coalesce(sum(i.line_total), 0) AS lifetime_value
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id
LEFT JOIN order_items i ON i.order_id = o.id
GROUP BY c.id, c.name;

ANALYZE;
